name: graphql_dart_codegen
description: Testing the generated graphql dart codes.
version: 1.0.0

environment:
  sdk: ^3.2.4

dependencies:
  http: ^1.1.2
  web_socket_channel: ^2.4.3
  uuid: ^4.2.1
  http_parser: ^4.0.2
  mime: ^1.0.5

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
